### ISSUE TITLE
Best repo ever. Thanks so much! 

### ISSUE THREAD

**Issue by bashleigh** [nrobinson2000/linux-blade#2]
:1st_place_medal:

**Comment by nrobinson2000** [comment]
Thanks.

If you have any suggestions for improvement feel free to make a pull request!

**Comment by bashleigh** [comment]
I could add my terminal setup but I think that comes down to personal perference? Not really razer related! Only issues I've had so far is the gestures but I'll look into that tomorrow :) Thanks again!
